//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> PC_ID { get; set; }
        public Nullable<int> VideoCard_ID { get; set; }
        public Nullable<int> Processor_ID { get; set; }
        public Nullable<int> Motherboard_ID { get; set; }
        public int Orders { get; set; }
        public int AcceptedOrder { get; set; }
        public Nullable<int> PC_Orders_Count { get; set; }
        public Nullable<int> VideoCard_Order_Count { get; set; }
        public Nullable<int> Processor_Order_Cout { get; set; }
        public Nullable<int> Motherboard_Order_Count { get; set; }
    
        public virtual Motherboard Motherboard { get; set; }
        public virtual Processor Processor { get; set; }
        public virtual Product Product { get; set; }
        public virtual VideoCard VideoCard { get; set; }
    }
}
