//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Cart = new HashSet<Cart>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ProductType { get; set; }
        public int ProcessorID { get; set; }
        public int VideoCardID { get; set; }
        public int BottomBoradID { get; set; }
        public string SystemType { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Cart { get; set; }
        public virtual Motherboard Motherboard { get; set; }
        public virtual Processor Processor { get; set; }
        public virtual VideoCard VideoCard { get; set; }
    }
}
